name: mpesadaraja
description: M-pesa daraja api library for flutter and dart. M-Pesa is a mobile phone-based money transfer.
version: 0.1.4
homepage: https://github.com/flavian-anselmo/mpesa-daraja-plugin-flutter-dart

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
